# Node.js v16.x
image: node:16.13-alpine3.12

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - lint
  - format

lint_check:
  stage: lint
  script:
    - yarn run lint
  except:
    - master
    - production

format_check:
  stage: format
  script:
    - yarn run format
  except:
    - master
    - production
